import frontImg from "./assets/images/productFront.webp";
import backImg from "./assets/images/productBack.webp";

export const newDesignProducts = [
  {
    id: 1,
    name: "Rockstar Game Gator",
    description:
      "his listing includes the Rockstar Game Gator Embroidery Design.  This is not a finished product, but only the digitized designs. Any photos of finished products associated with this post are for inspiration purposes only.",
    price: "5.95",
    productImages: {
      front: frontImg,
      back: backImg,
    },
  },
  {
    id: 2,
    name: "Rockstar Game Gator",
    description:
      "his listing includes the Rockstar Game Gator Embroidery Design.  This is not a finished product, but only the digitized designs. Any photos of finished products associated with this post are for inspiration purposes only.",
    price: "5.95",
    productImages: {
      front: frontImg,
      back: backImg,
    },
  },
  {
    id: 3,
    name: "Rockstar Game Gator",
    description:
      "his listing includes the Rockstar Game Gator Embroidery Design.  This is not a finished product, but only the digitized designs. Any photos of finished products associated with this post are for inspiration purposes only.",
    price: "5.95",
    productImages: {
      front: frontImg,
      back: backImg,
    },
  },
  {
    id: 4,
    name: "Rockstar Game Gator",
    description:
      "his listing includes the Rockstar Game Gator Embroidery Design.  This is not a finished product, but only the digitized designs. Any photos of finished products associated with this post are for inspiration purposes only.",
    price: "5.95",
    productImages: {
      front: frontImg,
      back: backImg,
    },
  },
  {
    id: 5,
    name: "Rockstar Game Gator",
    description:
      "his listing includes the Rockstar Game Gator Embroidery Design.  This is not a finished product, but only the digitized designs. Any photos of finished products associated with this post are for inspiration purposes only.",
    price: "5.95",
    productImages: {
      front: frontImg,
      back: backImg,
    },
  },
  {
    id: 6,
    name: "Rockstar Game Gator",
    description:
      "his listing includes the Rockstar Game Gator Embroidery Design.  This is not a finished product, but only the digitized designs. Any photos of finished products associated with this post are for inspiration purposes only.",
    price: "5.95",
    productImages: {
      front: frontImg,
      back: backImg,
    },
  },
  {
    id: 7,
    name: "Rockstar Game Gator",
    description:
      "his listing includes the Rockstar Game Gator Embroidery Design.  This is not a finished product, but only the digitized designs. Any photos of finished products associated with this post are for inspiration purposes only.",
    price: "5.95",
    productImages: {
      front: frontImg,
      back: backImg,
    },
  },
  {
    id: 8,
    name: "Rockstar Game Gator",
    description:
      "his listing includes the Rockstar Game Gator Embroidery Design.  This is not a finished product, but only the digitized designs. Any photos of finished products associated with this post are for inspiration purposes only.",
    price: "5.95",
    productImages: {
      front: frontImg,
      back: backImg,
    },
  },
  {
    id: 9,
    name: "Rockstar Game Gator",
    description:
      "his listing includes the Rockstar Game Gator Embroidery Design.  This is not a finished product, but only the digitized designs. Any photos of finished products associated with this post are for inspiration purposes only.",
    price: "5.95",
    productImages: {
      front: frontImg,
      back: backImg,
    },
  },
  {
    id: 10,
    name: "Rockstar Game Gator",
    description:
      "his listing includes the Rockstar Game Gator Embroidery Design.  This is not a finished product, but only the digitized designs. Any photos of finished products associated with this post are for inspiration purposes only.",
    price: "5.95",
    productImages: {
      front: frontImg,
      back: backImg,
    },
  },
  {
    id: 11,
    name: "Rockstar Game Gator",
    description:
      "his listing includes the Rockstar Game Gator Embroidery Design.  This is not a finished product, but only the digitized designs. Any photos of finished products associated with this post are for inspiration purposes only.",
    price: "5.95",
    productImages: {
      front: frontImg,
      back: backImg,
    },
  },
  {
    id: 12,
    name: "Rockstar Game Gator",
    description:
      "his listing includes the Rockstar Game Gator Embroidery Design.  This is not a finished product, but only the digitized designs. Any photos of finished products associated with this post are for inspiration purposes only.",
    price: "5.95",
    productImages: {
      front: frontImg,
      back: backImg,
    },
  },
];

export const shopOurProducts = [
  {
    id: 1,
    name: "Rockstar Game Gator",
    description:
      "his listing includes the Rockstar Game Gator Embroidery Design.  This is not a finished product, but only the digitized designs. Any photos of finished products associated with this post are for inspiration purposes only.",
    price: "5.95",
    count: 30,
    productImages: {
      front: frontImg,
      back: backImg,
    },
  },
  {
    id: 2,
    name: "Rockstar Game Gator",
    description:
      "his listing includes the Rockstar Game Gator Embroidery Design.  This is not a finished product, but only the digitized designs. Any photos of finished products associated with this post are for inspiration purposes only.",
    price: "5.95",
    count: 30,
    productImages: {
      front: frontImg,
      back: backImg,
    },
  },
  {
    id: 3,
    name: "Rockstar Game Gator",
    description:
      "his listing includes the Rockstar Game Gator Embroidery Design.  This is not a finished product, but only the digitized designs. Any photos of finished products associated with this post are for inspiration purposes only.",
    price: "5.95",
    count: 30,
    productImages: {
      front: frontImg,
      back: backImg,
    },
  },
  {
    id: 4,
    name: "Rockstar Game Gator",
    description:
      "his listing includes the Rockstar Game Gator Embroidery Design.  This is not a finished product, but only the digitized designs. Any photos of finished products associated with this post are for inspiration purposes only.",
    price: "5.95",
    count: 30,
    productImages: {
      front: frontImg,
      back: backImg,
    },
  },
  {
    id: 5,
    name: "Rockstar Game Gator",
    description:
      "his listing includes the Rockstar Game Gator Embroidery Design.  This is not a finished product, but only the digitized designs. Any photos of finished products associated with this post are for inspiration purposes only.",
    price: "5.95",
    count: 30,
    productImages: {
      front: frontImg,
      back: backImg,
    },
  },
  {
    id: 6,
    name: "Rockstar Game Gator",
    description:
      "his listing includes the Rockstar Game Gator Embroidery Design.  This is not a finished product, but only the digitized designs. Any photos of finished products associated with this post are for inspiration purposes only.",
    price: "5.95",
    count: 30,
    productImages: {
      front: frontImg,
      back: backImg,
    },
  },
  {
    id: 7,
    name: "Rockstar Game Gator",
    description:
      "his listing includes the Rockstar Game Gator Embroidery Design.  This is not a finished product, but only the digitized designs. Any photos of finished products associated with this post are for inspiration purposes only.",
    price: "5.95",
    count: 30,
    productImages: {
      front: frontImg,
      back: backImg,
    },
  },
  {
    id: 8,
    name: "Rockstar Game Gator",
    description:
      "his listing includes the Rockstar Game Gator Embroidery Design.  This is not a finished product, but only the digitized designs. Any photos of finished products associated with this post are for inspiration purposes only.",
    price: "5.95",
    count: 30,
    productImages: {
      front: frontImg,
      back: backImg,
    },
  },
  {
    id: 9,
    name: "Rockstar Game Gator",
    description:
      "his listing includes the Rockstar Game Gator Embroidery Design.  This is not a finished product, but only the digitized designs. Any photos of finished products associated with this post are for inspiration purposes only.",
    price: "5.95",
    count: 30,
    productImages: {
      front: frontImg,
      back: backImg,
    },
  },
  {
    id: 10,
    name: "Rockstar Game Gator",
    description:
      "his listing includes the Rockstar Game Gator Embroidery Design.  This is not a finished product, but only the digitized designs. Any photos of finished products associated with this post are for inspiration purposes only.",
    price: "5.95",
    count: 30,
    productImages: {
      front: frontImg,
      back: backImg,
    },
  },
  {
    id: 11,
    name: "Rockstar Game Gator",
    description:
      "his listing includes the Rockstar Game Gator Embroidery Design.  This is not a finished product, but only the digitized designs. Any photos of finished products associated with this post are for inspiration purposes only.",
    price: "5.95",
    count: 30,
    productImages: {
      front: frontImg,
      back: backImg,
    },
  },
  {
    id: 12,
    name: "Rockstar Game Gator",
    description:
      "his listing includes the Rockstar Game Gator Embroidery Design.  This is not a finished product, but only the digitized designs. Any photos of finished products associated with this post are for inspiration purposes only.",
    price: "5.95",
    count: 30,
    productImages: {
      front: frontImg,
      back: backImg,
    },
  },
];

export const shopPageProducts = [
  {
    id: 1,
    name: "Rockstar Game Gator",
    description:
      "his listing includes the Rockstar Game Gator Embroidery Design.  This is not a finished product, but only the digitized designs. Any photos of finished products associated with this post are for inspiration purposes only.",
    price: "5.95",
    count: 30,
    productImages: {
      front: frontImg,
      back: backImg,
    },
  },
  {
    id: 2,
    name: "Rockstar Game Gator",
    description:
      "his listing includes the Rockstar Game Gator Embroidery Design.  This is not a finished product, but only the digitized designs. Any photos of finished products associated with this post are for inspiration purposes only.",
    price: "5.95",
    count: 30,
    productImages: {
      front: frontImg,
      back: backImg,
    },
  },
  {
    id: 3,
    name: "Rockstar Game Gator",
    description:
      "his listing includes the Rockstar Game Gator Embroidery Design.  This is not a finished product, but only the digitized designs. Any photos of finished products associated with this post are for inspiration purposes only.",
    price: "5.95",
    count: 30,
    productImages: {
      front: frontImg,
      back: backImg,
    },
  },
  {
    id: 4,
    name: "Rockstar Game Gator",
    description:
      "his listing includes the Rockstar Game Gator Embroidery Design.  This is not a finished product, but only the digitized designs. Any photos of finished products associated with this post are for inspiration purposes only.",
    price: "5.95",
    count: 30,
    productImages: {
      front: frontImg,
      back: backImg,
    },
  },
  {
    id: 5,
    name: "Rockstar Game Gator",
    description:
      "his listing includes the Rockstar Game Gator Embroidery Design.  This is not a finished product, but only the digitized designs. Any photos of finished products associated with this post are for inspiration purposes only.",
    price: "5.95",
    count: 30,
    productImages: {
      front: frontImg,
      back: backImg,
    },
  },
  {
    id: 6,
    name: "Rockstar Game Gator",
    description:
      "his listing includes the Rockstar Game Gator Embroidery Design.  This is not a finished product, but only the digitized designs. Any photos of finished products associated with this post are for inspiration purposes only.",
    price: "5.95",
    count: 30,
    productImages: {
      front: frontImg,
      back: backImg,
    },
  },
  {
    id: 7,
    name: "Rockstar Game Gator",
    description:
      "his listing includes the Rockstar Game Gator Embroidery Design.  This is not a finished product, but only the digitized designs. Any photos of finished products associated with this post are for inspiration purposes only.",
    price: "5.95",
    count: 30,
    productImages: {
      front: frontImg,
      back: backImg,
    },
  },
  {
    id: 8,
    name: "Rockstar Game Gator",
    description:
      "his listing includes the Rockstar Game Gator Embroidery Design.  This is not a finished product, but only the digitized designs. Any photos of finished products associated with this post are for inspiration purposes only.",
    price: "5.95",
    count: 30,
    productImages: {
      front: frontImg,
      back: backImg,
    },
  },
  {
    id: 9,
    name: "Rockstar Game Gator",
    description:
      "his listing includes the Rockstar Game Gator Embroidery Design.  This is not a finished product, but only the digitized designs. Any photos of finished products associated with this post are for inspiration purposes only.",
    price: "5.95",
    count: 30,
    productImages: {
      front: frontImg,
      back: backImg,
    },
  },
  {
    id: 10,
    name: "Rockstar Game Gator",
    description:
      "his listing includes the Rockstar Game Gator Embroidery Design.  This is not a finished product, but only the digitized designs. Any photos of finished products associated with this post are for inspiration purposes only.",
    price: "5.95",
    count: 30,
    productImages: {
      front: frontImg,
      back: backImg,
    },
  },
  {
    id: 11,
    name: "Rockstar Game Gator",
    description:
      "his listing includes the Rockstar Game Gator Embroidery Design.  This is not a finished product, but only the digitized designs. Any photos of finished products associated with this post are for inspiration purposes only.",
    price: "5.95",
    count: 30,
    productImages: {
      front: frontImg,
      back: backImg,
    },
  },
  {
    id: 12,
    name: "Rockstar Game Gator",
    description:
      "his listing includes the Rockstar Game Gator Embroidery Design.  This is not a finished product, but only the digitized designs. Any photos of finished products associated with this post are for inspiration purposes only.",
    price: "5.95",
    count: 30,
    productImages: {
      front: frontImg,
      back: backImg,
    },
  },
];

export const newInStoreProducts = [
  {
    id: 1,
    name: "Rockstar Game Gator",
    description:
      "his listing includes the Rockstar Game Gator Embroidery Design.  This is not a finished product, but only the digitized designs. Any photos of finished products associated with this post are for inspiration purposes only.",
    price: "5.95",
    count: 30,
    productImages: {
      front: frontImg,
      back: backImg,
    },
  },
  {
    id: 2,
    name: "Rockstar Game Gator",
    description:
      "his listing includes the Rockstar Game Gator Embroidery Design.  This is not a finished product, but only the digitized designs. Any photos of finished products associated with this post are for inspiration purposes only.",
    price: "5.95",
    count: 30,
    productImages: {
      front: frontImg,
      back: backImg,
    },
  },
  {
    id: 3,
    name: "Rockstar Game Gator",
    description:
      "his listing includes the Rockstar Game Gator Embroidery Design.  This is not a finished product, but only the digitized designs. Any photos of finished products associated with this post are for inspiration purposes only.",
    price: "5.95",
    count: 30,
    productImages: {
      front: frontImg,
      back: backImg,
    },
  },
  {
    id: 4,
    name: "Rockstar Game Gator",
    description:
      "his listing includes the Rockstar Game Gator Embroidery Design.  This is not a finished product, but only the digitized designs. Any photos of finished products associated with this post are for inspiration purposes only.",
    price: "5.95",
    count: 30,
    productImages: {
      front: frontImg,
      back: backImg,
    },
  },
];

export const countriesData = [
  { code: "AF", name: "Afghanistan" },
  { code: "AX", name: "Åland Islands" },
  { code: "AL", name: "Albania" },
  { code: "DZ", name: "Algeria" },
  { code: "AS", name: "American Samoa" },
  { code: "AD", name: "Andorra" },
  { code: "AO", name: "Angola" },
  { code: "AI", name: "Anguilla" },
  { code: "AQ", name: "Antarctica" },
  { code: "AG", name: "Antigua and Barbuda" },
  { code: "AR", name: "Argentina" },
  { code: "AM", name: "Armenia" },
  { code: "AW", name: "Aruba" },
  { code: "AU", name: "Australia" },
  { code: "AT", name: "Austria" },
  { code: "AZ", name: "Azerbaijan" },
  { code: "BS", name: "Bahamas" },
  { code: "BH", name: "Bahrain" },
  { code: "BD", name: "Bangladesh" },
  { code: "BB", name: "Barbados" },
  { code: "BY", name: "Belarus" },
  { code: "PW", name: "Belau" },
  { code: "BE", name: "Belgium" },
  { code: "BZ", name: "Belize" },
  { code: "BJ", name: "Benin" },
  { code: "BM", name: "Bermuda" },
  { code: "BT", name: "Bhutan" },
  { code: "BO", name: "Bolivia" },
  { code: "BQ", name: "Bonaire, Saint Eustatius and Saba" },
  { code: "BA", name: "Bosnia and Herzegovina" },
  { code: "BW", name: "Botswana" },
  { code: "BR", name: "Brazil" },
  { code: "IO", name: "British Indian Ocean Territory" },
  { code: "BN", name: "Brunei" },
  { code: "BG", name: "Bulgaria" },
  { code: "BF", name: "Burkina Faso" },
  { code: "BI", name: "Burundi" },
  { code: "KH", name: "Cambodia" },
  { code: "CM", name: "Cameroon" },
  { code: "CA", name: "Canada" },
  { code: "CV", name: "Cape Verde" },
  { code: "KY", name: "Cayman Islands" },
  { code: "CF", name: "Central African Republic" },
  { code: "TD", name: "Chad" },
  { code: "CL", name: "Chile" },
  { code: "CN", name: "China" },
  { code: "CX", name: "Christmas Island" },
  { code: "CC", name: "Cocos (Keeling) Islands" },
  { code: "CO", name: "Colombia" },
  { code: "KM", name: "Comoros" },
  { code: "CG", name: "Congo (Brazzaville)" },
  { code: "CD", name: "Congo (Kinshasa)" },
  { code: "CK", name: "Cook Islands" },
  { code: "CR", name: "Costa Rica" },
  { code: "HR", name: "Croatia" },
  { code: "CU", name: "Cuba" },
  { code: "CW", name: "Curaçao" },
  { code: "CY", name: "Cyprus" },
  { code: "CZ", name: "Czech Republic" },
  { code: "DK", name: "Denmark" },
  { code: "DJ", name: "Djibouti" },
  { code: "DM", name: "Dominica" },
  { code: "DO", name: "Dominican Republic" },
  { code: "EC", name: "Ecuador" },
  { code: "EG", name: "Egypt" },
  { code: "SV", name: "El Salvador" },
  { code: "GQ", name: "Equatorial Guinea" },
  { code: "ER", name: "Eritrea" },
  { code: "EE", name: "Estonia" },
  { code: "SZ", name: "Eswatini" },
  { code: "ET", name: "Ethiopia" },
  { code: "FK", name: "Falkland Islands" },
  { code: "FO", name: "Faroe Islands" },
  { code: "FJ", name: "Fiji" },
  { code: "FI", name: "Finland" },
  { code: "FR", name: "France" },
  { code: "GF", name: "French Guiana" },
  { code: "PF", name: "French Polynesia" },
  { code: "TF", name: "French Southern Territories" },
  { code: "GA", name: "Gabon" },
  { code: "GM", name: "Gambia" },
  { code: "GE", name: "Georgia" },
  { code: "DE", name: "Germany" },
  { code: "GH", name: "Ghana" },
  { code: "GI", name: "Gibraltar" },
  { code: "GR", name: "Greece" },
  { code: "GL", name: "Greenland" },
  { code: "GD", name: "Grenada" },
  { code: "GP", name: "Guadeloupe" },
  { code: "GU", name: "Guam" },
  { code: "GT", name: "Guatemala" },
  { code: "GG", name: "Guernsey" },
  { code: "GN", name: "Guinea" },
  { code: "GW", name: "Guinea-Bissau" },
  { code: "GY", name: "Guyana" },
  { code: "HT", name: "Haiti" },
  { code: "HM", name: "Heard Island and McDonald Islands" },
  { code: "HN", name: "Honduras" },
  { code: "HK", name: "Hong Kong" },
  { code: "HU", name: "Hungary" },
  { code: "IS", name: "Iceland" },
  { code: "IN", name: "India" },
  { code: "ID", name: "Indonesia" },
  { code: "IR", name: "Iran" },
  { code: "IQ", name: "Iraq" },
  { code: "IE", name: "Ireland" },
  { code: "IM", name: "Isle of Man" },
  { code: "IL", name: "Israel" },
  { code: "IT", name: "Italy" },
  { code: "CI", name: "Ivory Coast" },
  { code: "JM", name: "Jamaica" },
  { code: "JP", name: "Japan" },
  { code: "JE", name: "Jersey" },
  { code: "JO", name: "Jordan" },
  { code: "KZ", name: "Kazakhstan" },
  { code: "KE", name: "Kenya" },
  { code: "KI", name: "Kiribati" },
  { code: "KW", name: "Kuwait" },
  { code: "KG", name: "Kyrgyzstan" },
  { code: "LA", name: "Laos" },
  { code: "LV", name: "Latvia" },
  { code: "LB", name: "Lebanon" },
  { code: "LS", name: "Lesotho" },
  { code: "LR", name: "Liberia" },
  { code: "LY", name: "Libya" },
  { code: "LI", name: "Liechtenstein" },
  { code: "LT", name: "Lithuania" },
  { code: "LU", name: "Luxembourg" },
  { code: "MO", name: "Macao" },
  { code: "MK", name: "North Macedonia" },
  { code: "MG", name: "Madagascar" },
  { code: "MW", name: "Malawi" },
  { code: "MY", name: "Malaysia" },
  { code: "MV", name: "Maldives" },
  { code: "ML", name: "Mali" },
  { code: "MT", name: "Malta" },
  { code: "MH", name: "Marshall Islands" },
  { code: "MQ", name: "Martinique" },
  { code: "MR", name: "Mauritania" },
  { code: "MU", name: "Mauritius" },
  { code: "YT", name: "Mayotte" },
  { code: "MX", name: "Mexico" },
  { code: "FM", name: "Micronesia" },
  { code: "MD", name: "Moldova" },
  { code: "MC", name: "Monaco" },
  { code: "MN", name: "Mongolia" },
  { code: "ME", name: "Montenegro" },
  { code: "MS", name: "Montserrat" },
  { code: "MA", name: "Morocco" },
  { code: "MZ", name: "Mozambique" },
  { code: "MM", name: "Myanmar (Burma)" },
  { code: "NA", name: "Namibia" },
  { code: "NR", name: "Nauru" },
  { code: "NP", name: "Nepal" },
  { code: "NL", name: "Netherlands" },
  { code: "NC", name: "New Caledonia" },
  { code: "NZ", name: "New Zealand" },
  { code: "NI", name: "Nicaragua" },
  { code: "NE", name: "Niger" },
  { code: "NG", name: "Nigeria" },
  { code: "NU", name: "Niue" },
  { code: "NF", name: "Norfolk Island" },
  { code: "KP", name: "North Korea" },
  { code: "MP", name: "Northern Mariana Islands" },
  { code: "NO", name: "Norway" },
  { code: "OM", name: "Oman" },
  { code: "PK", name: "Pakistan" },
  { code: "PS", name: "Palestinian Territories" },
  { code: "PA", name: "Panama" },
  { code: "PG", name: "Papua New Guinea" },
  { code: "PY", name: "Paraguay" },
  { code: "PE", name: "Peru" },
  { code: "PH", name: "Philippines" },
  { code: "PN", name: "Pitcairn Islands" },
  { code: "PL", name: "Poland" },
  { code: "PT", name: "Portugal" },
  { code: "PR", name: "Puerto Rico" },
  { code: "QA", name: "Qatar" },
  { code: "RE", name: "Réunion" },
  { code: "RO", name: "Romania" },
  { code: "RU", name: "Russia" },
  { code: "RW", name: "Rwanda" },
  { code: "WS", name: "Samoa" },
  { code: "SM", name: "San Marino" },
  { code: "ST", name: "São Tomé and Príncipe" },
  { code: "SA", name: "Saudi Arabia" },
  { code: "SN", name: "Senegal" },
  { code: "RS", name: "Serbia" },
  { code: "SC", name: "Seychelles" },
  { code: "SL", name: "Sierra Leone" },
  { code: "SG", name: "Singapore" },
  { code: "SX", name: "Sint Maarten" },
  { code: "SK", name: "Slovakia" },
  { code: "SI", name: "Slovenia" },
  { code: "SB", name: "Solomon Islands" },
  { code: "SO", name: "Somalia" },
  { code: "ZA", name: "South Africa" },
  { code: "GS", name: "South Georgia & South Sandwich Islands" },
  { code: "KR", name: "South Korea" },
  { code: "SS", name: "South Sudan" },
  { code: "ES", name: "Spain" },
  { code: "LK", name: "Sri Lanka" },
  { code: "BL", name: "St. Barthélemy" },
  { code: "SH", name: "St. Helena" },
  { code: "KN", name: "St. Kitts and Nevis" },
  { code: "LC", name: "St. Lucia" },
  { code: "MF", name: "St. Martin" },
  { code: "PM", name: "St. Pierre and Miquelon" },
  { code: "VC", name: "St. Vincent and Grenadines" },
  { code: "SD", name: "Sudan" },
  { code: "SR", name: "Suriname" },
  { code: "SJ", name: "Svalbard and Jan Mayen" },
  { code: "SE", name: "Sweden" },
  { code: "CH", name: "Switzerland" },
  { code: "SY", name: "Syria" },
  { code: "TW", name: "Taiwan" },
  { code: "TJ", name: "Tajikistan" },
  { code: "TZ", name: "Tanzania" },
  { code: "TH", name: "Thailand" },
  { code: "TL", name: "Timor-Leste" },
  { code: "TG", name: "Togo" },
  { code: "TK", name: "Tokelau" },
  { code: "TO", name: "Tonga" },
  { code: "TT", name: "Trinidad and Tobago" },
  { code: "TN", name: "Tunisia" },
  { code: "TR", name: "Türkiye" },
  { code: "TM", name: "Turkmenistan" },
  { code: "TC", name: "Turks and Caicos Islands" },
  { code: "TV", name: "Tuvalu" },
  { code: "UG", name: "Uganda" },
  { code: "UA", name: "Ukraine" },
  { code: "AE", name: "United Arab Emirates" },
  { code: "GB", name: "United Kingdom (UK)" },
  { code: "US", name: "United States (US)" },
  { code: "UY", name: "Uruguay" },
  { code: "UZ", name: "Uzbekistan" },
  { code: "VU", name: "Vanuatu" },
  { code: "VA", name: "Vatican" },
  { code: "VE", name: "Venezuela" },
  { code: "VN", name: "Vietnam" },
  { code: "WF", name: "Wallis and Futuna" },
  { code: "EH", name: "Western Sahara" },
  { code: "YE", name: "Yemen" },
  { code: "ZM", name: "Zambia" },
  { code: "ZW", name: "Zimbabwe" },
];



export const statesData = [
  { value: "AL", label: "Alabama" },
  { value: "AK", label: "Alaska" },
  { value: "AZ", label: "Arizona" },
  { value: "AR", label: "Arkansas" },
  { value: "CA", label: "California" },
  { value: "CO", label: "Colorado" },
  { value: "CT", label: "Connecticut" },
  { value: "DE", label: "Delaware" },
  { value: "DC", label: "District of Columbia" },
  { value: "FL", label: "Florida" },
  { value: "GA", label: "Georgia" },
  { value: "HI", label: "Hawaii" },
  { value: "ID", label: "Idaho" },
  { value: "IL", label: "Illinois" },
  { value: "IN", label: "Indiana" },
  { value: "IA", label: "Iowa" },
  { value: "KS", label: "Kansas" },
  { value: "KY", label: "Kentucky" },
  { value: "LA", label: "Louisiana" },
  { value: "ME", label: "Maine" },
  { value: "MD", label: "Maryland" },
  { value: "MA", label: "Massachusetts" },
  { value: "MI", label: "Michigan" },
  { value: "MN", label: "Minnesota" },
  { value: "MS", label: "Mississippi" },
  { value: "MO", label: "Missouri" },
  { value: "MT", label: "Montana" },
  { value: "NE", label: "Nebraska" },
  { value: "NV", label: "Nevada" },
  { value: "NH", label: "New Hampshire" },
  { value: "NJ", label: "New Jersey" },
  { value: "NM", label: "New Mexico" },
  { value: "NY", label: "New York" },
  { value: "NC", label: "North Carolina" },
  { value: "ND", label: "North Dakota" },
  { value: "OH", label: "Ohio" },
  { value: "OK", label: "Oklahoma" },
  { value: "OR", label: "Oregon" },
  { value: "PA", label: "Pennsylvania" },
  { value: "RI", label: "Rhode Island" },
  { value: "SC", label: "South Carolina" },
  { value: "SD", label: "South Dakota" },
  { value: "TN", label: "Tennessee" },
  { value: "TX", label: "Texas" },
  { value: "UT", label: "Utah" },
  { value: "VT", label: "Vermont" },
  { value: "VA", label: "Virginia" },
  { value: "WA", label: "Washington" },
  { value: "WV", label: "West Virginia" },
  { value: "WI", label: "Wisconsin" },
  { value: "WY", label: "Wyoming" },
  { value: "AA", label: "Armed Forces (AA)" },
  { value: "AE", label: "Armed Forces (AE)" },
  { value: "AP", label: "Armed Forces (AP)" }
];